.globl _BinkBufferBlit@12
.globl _BinkBufferCheckWinPos@12
.globl _BinkBufferClear@8
.globl _BinkBufferClose@4
.globl _BinkBufferGetDescription@4
.globl _BinkBufferGetError@0
.globl _BinkBufferLock@4
.globl _BinkBufferOpen@16
.globl _BinkBufferSetDirectDraw@8
.globl _BinkBufferSetHWND@8
.globl _BinkBufferSetOffset@12
.globl _BinkBufferSetResolution@12
.globl _BinkBufferSetScale@12
.globl _BinkBufferUnlock@4
.globl _BinkCheckCursor@20
.globl _BinkClose@4
.globl _BinkCloseTrack@4
.globl _BinkControlBackgroundIO@8
.globl _BinkControlPlatformFeatures@8
.globl _BinkCopyToBuffer@28
.globl _BinkCopyToBufferRect@44
.globl _BinkDDSurfaceType@4
.globl _BinkDX8SurfaceType@4
.globl _BinkDX9SurfaceType@4
.globl _BinkDoFrame@4
.globl _BinkDoFrameAsync@12
.globl _BinkDoFrameAsyncWait@8
.globl _BinkDoFramePlane@8
.globl _BinkGetError@0
.globl _BinkGetFrameBuffersInfo@8
.globl _BinkGetKeyFrame@12
.globl _BinkGetPalette@4
.globl _BinkGetRealtime@12
.globl _BinkGetRects@8
.globl _BinkGetSummary@8
.globl _BinkGetTrackData@8
.globl _BinkGetTrackID@8
.globl _BinkGetTrackMaxSize@8
.globl _BinkGetTrackType@8
.globl _BinkGoto@12
.globl _BinkIsSoftwareCursor@8
.globl _BinkLogoAddress@0
.globl _BinkNextFrame@4
.globl _BinkOpen@8
.globl _BinkOpenDirectSound@4
.globl _BinkOpenMiles@4
.globl _BinkOpenTrack@8
.globl _BinkOpenWaveOut@4
.globl _BinkPause@8
.globl _BinkRegisterFrameBuffers@8
.globl _BinkRequestStopAsyncThread@4
.globl _BinkRestoreCursor@4
.globl _BinkService@4
.globl _BinkSetError@4
.globl _BinkSetFrameRate@8
.globl _BinkSetIO@4
.globl _BinkSetIOSize@4
.globl _BinkSetMemory@8
.globl _BinkSetMixBinVolumes@20
.globl _BinkSetMixBins@16
.globl _BinkSetPan@12
.globl _BinkSetSimulate@4
.globl _BinkSetSoundOnOff@8
.globl _BinkSetSoundSystem@8
.globl _BinkSetSoundTrack@8
.globl _BinkSetVideoOnOff@8
.globl _BinkSetVolume@12
.globl _BinkShouldSkip@4
.globl _BinkStartAsyncThread@8
.globl _BinkWait@4
.globl _BinkWaitStopAsyncThread@4
.globl _RADTimerRead@0

_BinkBufferBlit@12:
    jmp ds:[_ADDR_TABLE + 0 * 4]
_BinkBufferCheckWinPos@12:
    jmp ds:[_ADDR_TABLE + 1 * 4]
_BinkBufferClear@8:
    jmp ds:[_ADDR_TABLE + 2 * 4]
_BinkBufferClose@4:
    jmp ds:[_ADDR_TABLE + 3 * 4]
_BinkBufferGetDescription@4:
    jmp ds:[_ADDR_TABLE + 4 * 4]
_BinkBufferGetError@0:
    jmp ds:[_ADDR_TABLE + 5 * 4]
_BinkBufferLock@4:
    jmp ds:[_ADDR_TABLE + 6 * 4]
_BinkBufferOpen@16:
    jmp ds:[_ADDR_TABLE + 7 * 4]
_BinkBufferSetDirectDraw@8:
    jmp ds:[_ADDR_TABLE + 8 * 4]
_BinkBufferSetHWND@8:
    jmp ds:[_ADDR_TABLE + 9 * 4]
_BinkBufferSetOffset@12:
    jmp ds:[_ADDR_TABLE + 10 * 4]
_BinkBufferSetResolution@12:
    jmp ds:[_ADDR_TABLE + 11 * 4]
_BinkBufferSetScale@12:
    jmp ds:[_ADDR_TABLE + 12 * 4]
_BinkBufferUnlock@4:
    jmp ds:[_ADDR_TABLE + 13 * 4]
_BinkCheckCursor@20:
    jmp ds:[_ADDR_TABLE + 14 * 4]
_BinkClose@4:
    jmp ds:[_ADDR_TABLE + 15 * 4]
_BinkCloseTrack@4:
    jmp ds:[_ADDR_TABLE + 16 * 4]
_BinkControlBackgroundIO@8:
    jmp ds:[_ADDR_TABLE + 17 * 4]
_BinkControlPlatformFeatures@8:
    jmp ds:[_ADDR_TABLE + 18 * 4]
_BinkCopyToBuffer@28:
    jmp ds:[_ADDR_TABLE + 19 * 4]
_BinkCopyToBufferRect@44:
    jmp ds:[_ADDR_TABLE + 20 * 4]
_BinkDDSurfaceType@4:
    jmp ds:[_ADDR_TABLE + 21 * 4]
_BinkDX8SurfaceType@4:
    jmp ds:[_ADDR_TABLE + 22 * 4]
_BinkDX9SurfaceType@4:
    jmp ds:[_ADDR_TABLE + 23 * 4]
_BinkDoFrame@4:
    jmp ds:[_ADDR_TABLE + 24 * 4]
_BinkDoFrameAsync@12:
    jmp ds:[_ADDR_TABLE + 25 * 4]
_BinkDoFrameAsyncWait@8:
    jmp ds:[_ADDR_TABLE + 26 * 4]
_BinkDoFramePlane@8:
    jmp ds:[_ADDR_TABLE + 27 * 4]
_BinkGetError@0:
    jmp ds:[_ADDR_TABLE + 28 * 4]
_BinkGetFrameBuffersInfo@8:
    jmp ds:[_ADDR_TABLE + 29 * 4]
_BinkGetKeyFrame@12:
    jmp ds:[_ADDR_TABLE + 30 * 4]
_BinkGetPalette@4:
    jmp ds:[_ADDR_TABLE + 31 * 4]
_BinkGetRealtime@12:
    jmp ds:[_ADDR_TABLE + 32 * 4]
_BinkGetRects@8:
    jmp ds:[_ADDR_TABLE + 33 * 4]
_BinkGetSummary@8:
    jmp ds:[_ADDR_TABLE + 34 * 4]
_BinkGetTrackData@8:
    jmp ds:[_ADDR_TABLE + 35 * 4]
_BinkGetTrackID@8:
    jmp ds:[_ADDR_TABLE + 36 * 4]
_BinkGetTrackMaxSize@8:
    jmp ds:[_ADDR_TABLE + 37 * 4]
_BinkGetTrackType@8:
    jmp ds:[_ADDR_TABLE + 38 * 4]
_BinkGoto@12:
    jmp ds:[_ADDR_TABLE + 39 * 4]
_BinkIsSoftwareCursor@8:
    jmp ds:[_ADDR_TABLE + 40 * 4]
_BinkLogoAddress@0:
    jmp ds:[_ADDR_TABLE + 41 * 4]
_BinkNextFrame@4:
    jmp ds:[_ADDR_TABLE + 42 * 4]
_BinkOpen@8:
    jmp ds:[_ADDR_TABLE + 43 * 4]
_BinkOpenDirectSound@4:
    jmp ds:[_ADDR_TABLE + 44 * 4]
_BinkOpenMiles@4:
    jmp ds:[_ADDR_TABLE + 45 * 4]
_BinkOpenTrack@8:
    jmp ds:[_ADDR_TABLE + 46 * 4]
_BinkOpenWaveOut@4:
    jmp ds:[_ADDR_TABLE + 47 * 4]
_BinkPause@8:
    jmp ds:[_ADDR_TABLE + 48 * 4]
_BinkRegisterFrameBuffers@8:
    jmp ds:[_ADDR_TABLE + 49 * 4]
_BinkRequestStopAsyncThread@4:
    jmp ds:[_ADDR_TABLE + 50 * 4]
_BinkRestoreCursor@4:
    jmp ds:[_ADDR_TABLE + 51 * 4]
_BinkService@4:
    jmp ds:[_ADDR_TABLE + 52 * 4]
_BinkSetError@4:
    jmp ds:[_ADDR_TABLE + 53 * 4]
_BinkSetFrameRate@8:
    jmp ds:[_ADDR_TABLE + 54 * 4]
_BinkSetIO@4:
    jmp ds:[_ADDR_TABLE + 55 * 4]
_BinkSetIOSize@4:
    jmp ds:[_ADDR_TABLE + 56 * 4]
_BinkSetMemory@8:
    jmp ds:[_ADDR_TABLE + 57 * 4]
_BinkSetMixBinVolumes@20:
    jmp ds:[_ADDR_TABLE + 58 * 4]
_BinkSetMixBins@16:
    jmp ds:[_ADDR_TABLE + 59 * 4]
_BinkSetPan@12:
    jmp ds:[_ADDR_TABLE + 60 * 4]
_BinkSetSimulate@4:
    jmp ds:[_ADDR_TABLE + 61 * 4]
_BinkSetSoundOnOff@8:
    jmp ds:[_ADDR_TABLE + 62 * 4]
_BinkSetSoundSystem@8:
    jmp ds:[_ADDR_TABLE + 63 * 4]
_BinkSetSoundTrack@8:
    jmp ds:[_ADDR_TABLE + 64 * 4]
_BinkSetVideoOnOff@8:
    jmp ds:[_ADDR_TABLE + 65 * 4]
_BinkSetVolume@12:
    jmp ds:[_ADDR_TABLE + 66 * 4]
_BinkShouldSkip@4:
    jmp ds:[_ADDR_TABLE + 67 * 4]
_BinkStartAsyncThread@8:
    jmp ds:[_ADDR_TABLE + 68 * 4]
_BinkWait@4:
    jmp ds:[_ADDR_TABLE + 69 * 4]
_BinkWaitStopAsyncThread@4:
    jmp ds:[_ADDR_TABLE + 70 * 4]
_RADTimerRead@0:
    jmp ds:[_ADDR_TABLE + 71 * 4]
